spring:

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/db/forum
    username: sa
    password:

  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console.enabled: true